#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

apt-get install -y ruby

# Grab Vanilla from upstream.
juju-log "Invoking the Virgo buildpack compile script"

cp -r vendor/virgo-buildpack/overlay-sample/* .

vendor/virgo-buildpack/bin/compile . /tmp

vendor/virgo-buildpack/bin/release . >start.sh

chmod +x start.sh

juju-log "Virgo installed"
