#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

juju-log "Starting Virgo"

#PORT=8080 /var/virgo/start.sh
cd /var/virgo
JAVA_HOME=$PWD/.java JAVA_OPTS="-Dhttp.port=8080 -XX:MaxPermSize=64M -XX:OnOutOfMemoryError=./.buildpack-diagnostics/killjava" .virgo/bin/startup.sh -clean
