#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

juju-log "Stopping Virgo"

cat /var/www/virgo/.pid | xargs kill -9
rm /var/www/virgo/.pid

juju-log "Stopped Virgo"
